# Generated by Django 2.2 on 2020-02-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.TextField(default='This is a description, jdskkdo djd jai djid, did hsjds, jdid udidi'),
            preserve_default=False,
        ),
    ]
