# Generated by Django 2.2 on 2020-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_prod',
            field=models.IntegerField(default=1),
        ),
    ]
