# Generated by Django 2.2 on 2020-02-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_num_of_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='num_of_prod',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='num_of_prod',
            field=models.IntegerField(default=1),
        ),
    ]
